version: '3.8'
services:
  bdjobs:
    image: postgres:13
    ports: 
      - 5434:5432
    environment:
      POSTGRES_USER: saaif
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp:

